#!/bin/bash

TIME=$(date +%Y-%m-%d_%H-%M-%S)

case "$1" in
	-h*|-H*)
		if [[ "$2" -ne "0" || -z "$2" ]]; then
			echo "usage: make-screencast <record | trim> <videofile> <start time hh:mm:ss> <end time hh:mm:ss>"
			echo "The script will record or trim the vidio, saving it as an mp4 file."
			echo "Run only once, not repeatedly on a file! Loss of quality will result!"
			exit
		fi
	;;
	trim)
		echo "file: $2, start: $3, end: $4"
		# Trim to specific start and end times in FFMPEG.
		ffmpeg -y \
			-noaccurate_seek \
			-ss "$3" \
			-i "$2" \
			-to "$4" \
			-acodec copy \
			-vcodec copy \
			-avoid_negative_ts make_zero \
			video_trimmed_$TIME.mp4
	;;
	record)	
		# capture screen data
		ffmpeg -y \
			-f x11grab \
			-s $(xdpyinfo | grep dimensions | awk '{print $2}') \
			-i :0.0 \
			-f pulse -ac 1 -ar 48000 \
			-i default \
			-filter_complex "compand=attacks=0:points=-60/-40|-30/-15|-15/-10|-5/-8|0/-6" \
			-c:v libx264 -r 30 \
			-c:a mp3 \
			video_capture_$TIME.mp4
	;;
esac
