#!/bin/bash

# Copyright (c) 2021 by Philip Collier, radio AB9IL
# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version. There is NO warranty; not even for
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# Automatically load KiwiSDR sites to monitor something
#
# NOTES:
#  1) Enter the servers as a list of strings separated by
#      a single space:  "url frequency mode"
#  2) Urls contain the domain, subdomain (if used),
#     the port number, and trailing slash "/" (always used)
#  3) Use lower case letters for the mode: "cw", "lsb", "am"
#  4) The preferred AM mode is synchronous AM; any mode
#     set to "am" will be automatically switched to "sam"
#  5) CW mode will default to "usb" with an 800 Hz offset
#     and a bandpass of 600 to 1000 Hz.
#  6) Extended Single Sideband is set for an 8000 Hz banpass.
#     It should be designated as "lsbw" or "usbw".
#
# Example: 
# Channel_1='"Atlantic Routes"
# "http://raleigh.twrmon.net:8073/ 6577.00 usb"
# "http://bottlebranch.proxy.kiwisdr.com:8073/ 6577.00 usb"'
#
# Specify the web browser command
browser='firefox --new-window'

# Set up the channels 
Channel_1='"Western Atlantic Routes"
"http://raleigh.twrmon.net:8073/ 6577.00 usb"
"http://bottlebranch.proxy.kiwisdr.com:8073/ 6577.00 usb"'

Channel_2='"Eastern Pacific Routes"
"http://kfs.wsprdaemon.org:8083/ 5547.00 usb"
"http://75.144.20.99:8073/ 5574.00 usb"'

Channel_3='"HFGCS West"
"http://kr6la.proxy.kiwisdr.com:8073/ 11175.00 usb"
"http://n0emp.ddns.net:8073/ 11175.00 usb"'

Channel_4='"HFGCS East"
"http://65.29.124.73:8073/ 11175.00 usb"
"http://raleigh.twrmon.net:8073/ 11175.00 usb"'

Channel_5='"CJAD Montreal (English)"
"http://ymartin.com:8073/ 800.00 am"'

Channel_6='"CFNV Montreal (French)"
"http://ymartin.com:8073/ 940.00 am"'

Channel_7='"CFRA Ottawa (English)"
"http://ve3hoa.ddns.net:8073/ 580.00 am"'

Channel_8='"CKAC Montreal (French)" 
"http://ve3hoa.ddns.net:8073/ 730.00 am"'

Channel_9='"WILL Champaign-Urbana"
"http://radio.ofadam.com:8073/ 580.00 am"'

Channel_10='"WNYC New York"
"http://73.150.139.247:8073/ 820.00 am"'

Channel_11='"WHA Madison Wisconsin"
"http://k9dxi.zapto.org:8073/ 970.00 am"'

Channel_12='"BBC Radio 4 Longwave"
"http://g4gnk.proxy.kiwisdr.com:8073/ 198.00 am"'

Channel_13='"Indochina Aeroband Pirate"
"http://ptlensdr.ddns.net:8073/ 8812.00 usb"
"http://du6-pe1nsq.proxy.kiwisdr.com:8073/ 8812.00 usb"'

Channel_14='"3630 Extended Single Sideband"
"http://k9dxi.zapto.org:8073/ 3630.00 lsbw"'

###############################################################################
# CAUTION: DRAGONS LIVE BELOW THIS LINE
###############################################################################
[[ "$1" == "gui" ]] && COMMAND="rofi -dmenu -p Select"
[[ "$1" == "gui" ]] || COMMAND="fzf --layout=reverse --header=Select:"

# Select the desired Channel
# Use brace expansion, sed, and awk
CHOICE=$(echo -e $Channel_{1..14}\\n | sed 's/^ //g' | sed '/^$/d' | \
    awk -F\" '{printf $2"\n"}' | $COMMAND )

[[ -z "$CHOICE" ]] && echo "No selection made, exiting..." && exit 0

# Get site urls, freq, and mode for the desired channel
# Use brace expansion and grep
CHECK=$(echo -e $Channel_{1..14}\\n | grep "$CHOICE")

start_radio(){
for target in field; do
    # extract url fragments from target
    url=$(echo $field | awk '{printf $1}')
    freq=$(echo $field | awk '{printf $2}')
    mode=$(echo $field | awk '{printf $3}')
done

# make mode lower case; set bandpass and zoom
mode="${mode,,}"
[[  "$mode" == "cw" ]] && mode="usb" && bandpass="600,1000" && \
    freq=$(echo "$freq - 0.8" | bc) && zoom="z13"
[[  "$mode" == "usb" ]] && bandpass="100,3500" && zoom="z13"
[[  "$mode" == "usbw" ]] && bandpass="10,8000" && zoom="z10" && mode="usb"
[[  "$mode" == "lsb" ]] && bandpass="-3500,-100" && zoom="z13"
[[  "$mode" == "lsbw" ]] && bandpass="-8000,-10" && zoom="z10" && mode="lsb"
[[  "$mode" == "am" ]] && mode="sam" && bandpass="-4000,4000" && zoom="z10"

# open the browser and connect to the SDR server
$browser $url"?f="$freq"/"$bandpass$mode$zoom &
}

field=$(echo $CHECK | awk -F\" '{printf $4"\n"}')
[[ -z "$field"  ]] || start_radio

field=$(echo $CHECK | awk -F\" '{printf $6"\n"}')
[[ -z "$field"  ]] || start_radio

